### ISSUE TITLE
Missing Metal Gear Solid 2 - Sons of Liberty (USA)

### ISSUE THREAD

**Issue by cameron-ostrom** [libretro-thumbnails/Sony_-_PlayStation_2#39]
As said above, there isn't box art for the above version of this game

**Comment by marimbaboy** [comment]
![Metal Gear Solid 2 - Sons of Liberty (USA)](https://user-images.githubusercontent.com/106387302/233998613-460426ba-8b3a-467d-a4d2-a04780e53671.png)

**Comment by marimbaboy** [comment]
It looks like it's using the wrong region boxart

https://thumbnails.libretro.com/Sony%20-%20PlayStation%202/Named_Boxarts/Metal%20Gear%20Solid%202%20-%20Sons%20of%20Liberty%20%28USA%29.png

**Comment by RobLoach** [comment]
Looks like those ones are missing `serial` #s, so it makes sense why they don't show up.

**Comment by RobLoach** [comment]
Thanks for the fix!
